version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=y
            - EXECUTOR=Local
        volumes:
            - /Users/richardhe/MVF/REPOS/bi:/usr/local/airflow/bi
            - /tmp/aw-reporting:/usr/local/data/aw-reporting
        ports:
            - "8080:8080"
        command: webserver
